# Generated by Django 3.2.6 on 2021-09-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'test_verbose_nmae', 'verbose_name_plural': 'test_verbose_nmae_plural'},
        ),
    ]
